repos:
  - repo: local
    hooks:
      - id: generate-commit-message
        name: Generate Commit Message
        entry: gemini generate_commit_message
        language: system
        stages: [commit-msg]